version: "3.9"
   
services:

  bot:
    build: .
    container_name: telegram_bot
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - "443:443"
      - "80:80"
      - "88:88"
      - "8448:8448"
